services:
  pqc-gen:
    build: .
    user: "${CURRENT_UID}:${CURRENT_GID}"
    volumes:
      - ./out:/output
    environment:
      - JAVA_OPTS=-Dcsr.outdir=/output -Dcsr.subject=CN=PQC-Universal-Test,O=Keyfactor,C=US
    command: ["ML-DSA-87"]